// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkbblivedlrhbambafao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrYmJsaXZlZGxyaGJhbWJhZmFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODU1NTYsImV4cCI6MjA2ODY2MTU1Nn0.TUt0LBU-TyrMkl7TzcdyeN-ksmb4gE8xJUSJPLtTyfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});